export const REQUEST_MESSAGES = 'REQUEST_MESSAGES';
export const RECEIVE_MESSAGES = 'RECEIVE_MESSAGES';

export const REQUEST_THREAD = 'REQUEST_THREAD';
export const RECEIVE_THREAD = 'RECEIVE_THREAD';

export const REQUEST_THREADS = 'REQUEST_THREADS';
export const RECEIVE_THREADS = 'RECEIVE_THREADS';
export const LOAD_MORE_THREADS = 'LOAD_MORE_THREADS';
export const INVALIDATE_THREADS = 'INVALIDATE_THREADS';

export const REQUEST_CONTACT = 'REQUEST_CONTACT';
export const RECEIVE_CONTACT = 'RECEIVE_CONTACT';

export const SELECT_CONTACT = 'SELECT_CONTACT';
export const REQUEST_CONTACTS = 'REQUEST_CONTACTS';
export const RECEIVE_CONTACTS = 'RECEIVE_CONTACTS';
export const LOAD_MORE_CONTACTS = 'LOAD_MORE_CONTACTS';
export const INVALIDATE_CONTACTS = 'INVALIDATE_CONTACTS';

export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const UPDATE_CONTACT_SUCCEED = 'UPDATE_CONTACT_SUCCEED';
export const UPDATE_CONTACT_FAILED = 'UPDATE_CONTACT_FAILED';

export const ADD_CONTACT_DETAIL = 'ADD_CONTACT_DETAIL';
export const ADD_CONTACT_DETAIL_FAILED = 'ADD_CONTACT_DETAIL_FAILED';
export const ADD_CONTACT_DETAIL_SUCCEEDED = 'ADD_CONTACT_DETAIL_SUCCEEDED';
export const DELETE_CONTACT_DETAIL = 'DELETE_CONTACT_DETAIL';
export const DELETE_CONTACT_DETAIL_SUCCEEDED = 'DELETE_CONTACT_DETAIL_SUCCEEDED';
export const DELETE_CONTACT_DETAIL_FAILED = 'DELETE_CONTACT_DETAIL_FAILED';

export const REQUEST_CONTACT_PROTOCOLS = 'REQUEST_CONTACT_PROTOCOLS';
export const RECEIVE_CONTACT_PROTOCOLS = 'RECEIVE_CONTACT_PROTOCOLS';

export const REQUEST_TABS = 'REQUEST_TABS';
export const ADD_TAB = 'ADD_TAB';
export const REMOVE_TAB = 'REMOVE_TAB';
export const SELECT_OR_ADD_TAB = 'SELECT_OR_ADD_TAB';

export const REQUEST_USER = 'REQUEST_USER';
export const RECEIVE_USER = 'RECEIVE_USER';

export const INVALIDATE_USER = 'INVALIDATE_USER';

export const RECEIVE_REMOTE_IDENTITY = 'RECEIVE_REMOTE_IDENTITY';
export const ADD_REMOTE_IDENTITY = 'ADD_REMOTE_IDENTITY';
export const UPDATE_REMOTE_IDENTITY = 'UPDATE_REMOTE_IDENTITY';
export const CONNECT_REMOTE_IDENTITY = 'CONNECT_REMOTE_IDENTITY';
export const DISCONNECT_REMOTE_IDENTITY = 'DISCONNECT_REMOTE_IDENTITY';

export const CREATE_DRAFT_MESSAGE = 'CREATE_DRAFT_MESSAGE';
export const UPDATE_DRAFT_MESSAGE = 'UPDATE_DRAFT_MESSAGE';

export const SWITCH_APPLICATION = 'SWITCH_APPLICATION';

export const UPDATE_PRIVACY_INDEX_RANGE = 'UPDATE_PRIVACY_INDEX_RANGE';
export const UPDATE_IMPORTANCE_LEVEL_RANGE = 'UPDATE_IMPORTANCE_LEVEL_RANGE';
