export const SELECT_THREAD = 'SELECT_THREAD';
export const REQUEST_MESSAGES = 'REQUEST_MESSAGES';
export const RECEIVER_MESSAGES = 'RECEIVER_MESSAGES';
export const REQUEST_THREADS = 'REQUEST_THREADS';
export const RECEIVER_THREADS = 'RECEIVER_THREADS';
