export const SELECT_THREAD = 'SELECT_THREAD';
export const REQUEST_MESSAGES = 'REQUEST_MESSAGES';
export const RECEIVER_MESSAGES = 'RECEIVER_MESSAGES';
export const REQUEST_THREADS = 'REQUEST_THREADS';
export const RECEIVER_THREADS = 'RECEIVER_THREADS';

export const SELECT_CONTACT = 'SELECT_THREAD';
export const REQUEST_CONTACTS = 'REQUEST_CONTACTS';
export const RECEIVER_CONTACTS = 'RECEIVER_CONTACTS';
